/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins {
    java
    checkstyle
}

repositories {
    mavenCentral()
}

checkstyle {
    val archive = configurations.checkstyle.get().resolve().filter {
        it.name.startsWith("checkstyle")
    }
    config = resources.text.fromArchiveEntry(archive, "google_checks.xml")
}

dependencies {
  testImplementation(platform("org.junit:junit-bom:5.10.1"))
  testImplementation("org.junit.jupiter:junit-jupiter")
  testRuntimeOnly("org.junit.platform: junit-platform-launcher")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
tasks.named<JavaCompile>("compileTestJava") {
    doFirst {
        classpath.forEach{
            println(it)
        }
        sourceSets.named("test").get().let {
            println(it);
        }
    }
}